// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsucXi-xQCB225rAoL7Y_0BUArrniYVUo',
    appId: '1:26323609053:android:fcc1cb7047e2c577c34234',
    messagingSenderId: '26323609053',
    projectId: 'hi-sudoku-7e6cf',
    storageBucket: 'hi-sudoku-7e6cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdlJNsE7qwFmfDxneGegxQolydGuZVYGI',
    appId: '1:26323609053:ios:3d5f410f41530074c34234',
    messagingSenderId: '26323609053',
    projectId: 'hi-sudoku-7e6cf',
    storageBucket: 'hi-sudoku-7e6cf.appspot.com',
    androidClientId: '26323609053-uuc3ve3flb5f2hemdhacsnj6q8upbnch.apps.googleusercontent.com',
    iosClientId: '26323609053-2qc9oev2fga2rii3lungff92bju9tpmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiSudoku',
  );
}
